### ISSUE TITLE
dot_publicparking	

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#10]
- [x] s3
- [ ] py
- [ ] sql

**Comment by AmandaDoyle** [comment]
Shapefile dot_municipalparking uploaded to /agencysourcedata/dot

**Comment by baolingz** [comment]
@SPTKL cannot load dataset from s3 by using 5-31 url

**Comment by baolingz** [comment]
@SPTKL s3 loading issue has been solved after removing the data checkpoints
