### ISSUE TITLE
nysoasas_programs

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#100]
- [x] s3 
- [ ] py
- [ ] sql

NYS OASAS-Certified Chemical Dependence Treatment Programs
https://www.oasas.ny.gov/providerDirectory/index.cfm?search_type=2
need locations within 5 boroughs
Can download spreadsheet

after inspecting network traffic: 
https://www.oasas.ny.gov/providerDirectory/download/Treatment_Providers_OASAS_Directory_Search_11-Jun-19.csv

**Comment by SPTKL** [comment]
source data doesn't contain NYC records, fix from db-data-recipes

**Comment by SPTKL** [comment]
url updated to: 
https://www.oasas.ny.gov/providerDirectory/download/Treatment_Providers_OASAS_Directory_Search_29-Jul-19.csv
resolved
