### ISSUE TITLE
doe_bluebook

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#104]
- [x] s3
- [ ] sql
- [ ] py

**Comment by mshapiro1** [comment]
@AmandaDoyle 

For school-based data in FacDB, we should be using an Open Data source. We can use the Open Data source of Blue Book (https://data.cityofnewyork.us/Education/Enrollment-Capacity-And-Utilization-Reports-Target/gkd7-3vk7).

We can also use LCGMS, which is updated more frequently (https://data.cityofnewyork.us/Education/LCGMS-DOE-School-Information-Report/3bkj-34v2)

**Comment by AmandaDoyle** [comment]
@mshapiro1 Thanks for confirming
Currently we munge LCGMS and Blue Book together in FacDB, but once we refactor the codebase we can revisit how we're utilizing these two datasets

@baolingz @bendnorman Green flag to use https://data.cityofnewyork.us/Education/Enrollment-Capacity-And-Utilization-Reports-Target/8b9a-pywy as the source for Blue Book data

**Comment by SPTKL** [comment]
@AmandaDoyle current dataset doesn't have address info

**Comment by bendnorman** [comment]
Munged the two together to get address info: https://github.com/NYCPlanning/db-facilities-tmp/blob/notebooks/notebooks/doe_bluebook.ipynb
