### ISSUE TITLE
dcp_sfpsd

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#107]
- [x] s3
- [x] py
- [x] sql

There are a handful of Facilities that we have not found the original source data for on open data or from an agency contact, so take the records from the former Facilities database where pgtable equals one of the following values
amtrak_facilities_sfpsd
bbpc_facilities_sfpsd
hrpt_facilities_sfpsd
mta_facilities_sfpsd
nysdot_facilities_sfpsd
panynj_facilities_sfpsd
tgi_facilities_sfpsd
dcas_facilities_colp;rioc_facilities_sfpsd

Can download data from capital planning platform https://capitalplanning.nyc.gov/facilities
or Bytes https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-selfac.page

**Comment by baolingz** [comment]
@SPTKL mta_facilities_sfpsd hasn't been loaded into facilities.
https://github.com/NYCPlanning/db-facilities-tmp/blob/dev/etl/dcp_sfpsd.py

**Comment by baolingz** [comment]
Host the dcp_sfpsd dataset on `db-data-recipes` github and load this manually maintained dataset into s3

**Comment by SPTKL** [comment]
include the following pgtable: 
```
amtrak_facilities_sfpsd
bbpc_facilities_sfpsd
dcas_facilities_colp;mta_facilities_sfpsd
dcas_facilities_colp;rioc_facilities_sfpsd
hrpt_facilities_sfpsd
mta_facilities_sfpsd
nysdot_facilities_sfpsd
panynj_facilities_sfpsd
tgi_facilities_sfpsd
```
