### ISSUE TITLE
dpr_parksproperties sql script needs editing 

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#11]
- [x] s3
- [x] build.py 
- [x] .sql

https://github.com/NYCPlanning/db-facilities/blob/master/2_assembly/config_dpr_parksproperties.sql

**Comment by baolingz** [comment]
Centroid need to be calculated.

**Comment by baolingz** [comment]
@SPTKL Review Request

**Comment by SPTKL** [comment]
```
ALTER TABLE
psql:/home/db-facilities/sql/dpr_parksproperties.sql:63: ERROR:  syntax error at or near "        "
LINE 7:                 END),
        ^
```

unable to execute sql script

**Comment by SPTKL** [comment]
Fixed, 
for future reference, if we want to use existing geometry for the records that didn't geocode, do the following:
```sql
wkb_geometry = (CASE
        WHEN wkb_geometry is NULL 
            THEN ST_SetSRID(ST_Centroid(existing geometry), 4326)
        ELSE wkb_geometry
    END),
```
