### ISSUE TITLE
removing records from outside of NYC

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#125]
ideas: 
- add a where statement at the end of the stored procedure: 
```
select * from (select geo::json->'results'->>'GRC' as grc from nysoasas_programs) t 
where grc = '71';
```
- note that GRC = '71' corresponds to `INPUT ZIP CODE IS NOT A NEW YORK CITY ZIP CODE`
- potential issues: for datasets that skipped the geocoding process, it might be tricky since they don't have all these columns retrieved from geosupport

**Comment by AmandaDoyle** [comment]
There are records that still fall outside of NYC
Might need to clip to borough boundary with water

**Comment by SPTKL** [comment]
```
DELETE FROM facilities WHERE 
facilities.uid IN (
    SELECT a.uid FROM
      facilities a, (
           SELECT ST_Union(wkb_geometry) As geom FROM dcp_boroboundaries_wi
      ) b
      WHERE ST_Disjoint(a.geom, b.geom)
 );
```
works, but a bit slow

**Comment by AmandaDoyle** [comment]
Slow is okay - do you want to implement and republish quickly?

**Comment by SPTKL** [comment]
I was wondering what's the difference between above and 
```
DELETE FROM facilities WHERE 
facilities.uid NOT IN (
    SELECT a.uid FROM
      facilities a, (
           SELECT ST_Union(wkb_geometry) As geom FROM dcp_boroboundaries_wi
      ) b
      WHERE ST_Within(a.geom, b.geom)
 );
```

**Comment by AmandaDoyle** [comment]
ST_Disjoint is touches the other boundary,
ST_Within is it's totally within the other boundary
The issue may be that you're working with multi point geometries and you need to do ST_Dump to go from multi to single point
