### ISSUE TITLE
POPS unique id is needed for POPS Explorer

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/db-facilities-tmp#138]
The POPS Explorer requires that each POPS profile have the preferred POPS ID in the URL. FacDB needs to provide the POPS unique ID instead of or in addition to the uid. The POPS ID could overwrite the uid or be included in an extra column that only Labs uses.

Example: https://capitalplanning.nyc.gov/pops/M050092

**Comment by AmandaDoyle** [comment]
Updating the hash value to be the pops_number for records from dcp_pops so that FacDB is compatible with the POPs explorer
