### ISSUE TITLE
doe_busroutesgarages duplicate records

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/db-facilities-tmp#140]
The doe_busroutesgarages dataset is providing duplicate records.

Example: 
`SELECT * FROM dcpadmin.facilities_1 where facname = 'Jofaz Transportation Inc.' and addressnum = '2037'`

For this specific example ^ it also seems like the apostrophe in P'WAY is keeping the record from getting geocoded.

**Comment by SPTKL** [comment]
- each bus route will get their own row, however they can be owned by the same/different vendor parked at the same garage
- since vendor related information will not appear in the facilities database, we can deduplicate based on addresses

**Comment by SPTKL** [comment]
```
SELECT
   DISTINCT ON (garage__street_address, garage_city, garage_state, zipcode, vendor_name) *
FROM doe_busroutesgarages;
```
