### ISSUE TITLE
Records from several datasets are missing "facdomain" and "facgroup"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/db-facilities-tmp#141]
They're coming from
- [ ] dcas_colp
- [ ] dohmh_daycare
- [ ] nycha_communitycenters
- [ ] nysdoccs_corrections

```
SELECT facdomain, facgroup, datasource, count(*)
FROM dcpadmin.facilities_1
where facdomain = '' or facgroup = ''
group by facdomain, facgroup, datasource
order by facdomain, facgroup, datasource
```

**Comment by SPTKL** [comment]
- nysdoccs_corrections: changed `correctional facilities` to `detention and correctional`
- dohmh_daycare: `day care` to `child care`
- dcas_colp: `office` to `offices`
- nycha_communitycenters: not sure why it's not working
