### ISSUE TITLE
Develop QAQC report that compares new database to previous FacDB

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#143]

**Comment by AmandaDoyle** [comment]
First 2 reports
Summary stats by data source
data source, count in new DB, count or percent in new DB with geometry, count in old DB,  count or percent in old DB with geometry

Summary stats by facility subgroup
count in new DB, count or percent in new DB with geometry, count in old DB,  count or percent in old DB with geometry, subgroup, group, domain

**Comment by baolingz** [comment]
https://github.com/NYCPlanning/db-facilities-tmp/blob/qaqc/facdb_qaqc.ipynb
