### ISSUE TITLE
usdot_ports - want to drop some records

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#146]
There are clearly some records that do not below in the Facilities Database from this dataset such as Tompkinsville S I Anchorage, Harlem River Tows, Bulkhead Btwn E 127 St& 128 St

Maybe only include records where facname does not include, Anchorage, Tows, or Bulkhead, and any other keyword that indicate it's not a ferry landing or port.  Or if it's easier more accurate the opposite and only include records with keywords that indicate that it's clearly a port of terminal

**Comment by SPTKL** [comment]
```
select * from usdot_ports where nav_unit_n ~* '^port|terminal|ferry';
```

**Comment by AmandaDoyle** [comment]
@SPTKL Thank you!
