### ISSUE TITLE
Redo order of fields

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#147]
[FacDB field order.xlsx](https://github.com/NYCPlanning/db-facilities-tmp/files/3350565/FacDB.field.order.xlsx)

Publish the columns in the order in the file attached

**Comment by AmandaDoyle** [comment]
This issue has not been resolved

Fields should be in the order outlined in the `Proposed field order` column in the spreadsheet

**Comment by baolingz** [comment]
@AmandaDoyle  In the `proposed field order` there's no `geom`, `BoroCode`, `SchoolDist` and `PolicePrct`, where should I put them?

**Comment by AmandaDoyle** [comment]
`geom` at the end
then

ZIPCODE
BORO
`BoroCode`
BIN
BBL
COMMBOARD
NTA
COUNCIL
`SchoolDist`
`PolicePrct`
CENSTRACT
FACTYPE

**Comment by AmandaDoyle** [comment]
Confirmed corrected
