### ISSUE TITLE
Records that have an address do not have a boro

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#171]
i.e. uid: 4c2e5c771cc4720e79fa1cdb431eeaef

**Comment by AmandaDoyle** [comment]
Also, we should only be backfilling for the address field and housenum and streetname should only come from Geosupport

**Comment by SPTKL** [comment]
- ` housenum and streetname` are always coming from geosupport 
- if an address doesn't have valid bbl correspond to it, it would have empty boro --> fixed, need to regeocode all datasets
