### ISSUE TITLE
Spatially assign geo boundaries where record has geometry but the geom bound info is NULL

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#172]
If zipcode, boro, borocode, commboard, nta, council, schooldist, policeprct, or censtract is NULL and geom IS NOT NULL spitally assign geographic boundary

Follow logic found here
https://github.com/NYCPlanning/db-developments/blob/master/developments_build/sql/spatialjoins.sql

**Comment by AmandaDoyle** [comment]
Implemented

**Comment by baolingz** [comment]
Need to double-check the spatial join process for `censtract`
```
SELECT COUNT(*) 
FROM facilities
WHERE censtract = '000900';
------
count
12917
```

**Comment by SPTKL** [comment]
fixed, 

previously, all null geometries got assigned into 000900
SELECT COUNT(*) 
FROM facilities
WHERE censtract = '000900';
------
count
387
