### ISSUE TITLE
School bus depots - remove duplicates

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#175]
Description
Each row in the source dataset is a bus route originating at a specific garage. FacDB should have one record per garage. This will reduce the number of records from > 4000 to < 100.

Consider updating the capacity field with the number of routes originating in that garage.

Requestor
Lynn

https://github.com/NYCPlanning/db-facilities/issues/286

**Comment by SPTKL** [comment]
@lseirup @AmandaDoyle 
how do we determine the facility name and operator name?
the only feature identifying the facility is the address and there could be multiple operators at the same facility under different affiliations.
capacity type  -> `routes`?

**Comment by lseirup** [comment]
@AmandaDoyle @SPTKL  The source dataset has vendor_name, which is what we're currently using for both facility name and operator name.

**Comment by AmandaDoyle** [comment]
@SPTKL 
capacity type = routes
is correct

**Comment by AmandaDoyle** [comment]
@lseirup 
In this case
https://capitalplanning.nyc.gov/facility/104490#15.89/40.6794/-73.9071
Where there are 3 school bus depots at the same location, which vendor name should we take?

**Comment by lseirup** [comment]
@AmandaDoyle I think we should show a facility record for each vendor at the location (at least for now)
