### ISSUE TITLE
Add one more geocoding step to geocode to centerline

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#178]
1) geocode to lot
2) get geometry from source data
new: 
3) if address can geocode to centerline take lat / long from geosupport and map to centerline (i.e. 1326 RALPH AVENUE).  Fill in geom, lat, long, x, and y fields (and all other attributes that are assigned from geosupport or spatial join)
4) Set up error reporting to GRU for 1B calls that partially fail (export records that do not geocode to lot but geocode to centerline)

**Comment by SPTKL** [comment]
this is completed, only about 589 records fits the above requirements and geocoded to centerline
