### ISSUE TITLE
Facname - Convert to all caps

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#179]
Convert to all caps (for now)
Currently there is a mixture of caps and mixed case
Introduced errors, e.g., in source data for school bus depots, the vendor name is all caps. 
In FacDB, it’s mixed case with errors such as “Bobby’S Bus Co., Inc.

**Comment by SPTKL** [comment]
```
UPDATE facilities a
SET facname = UPPER(facname);
```
