### ISSUE TITLE
doe_busroutesgarages

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#183]
doe_busroutesgarages, but probably applies to other datasets
- What do we do with addresses outside the city? These have x,y values, so could be mapped.
Remove records that are outside of NYC
- Remove records with no address or x,y values in the source data?
TDB
@amirapu ^ should records with no address or spatial data be removed?

**Comment by baolingz** [comment]
All records with addresses outside NYC will be filtered out before being loaded into `facilities` by checking against GRC code 71, which can be found in load_to_facilities.sql
