### ISSUE TITLE
Assign geometry based on source data

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-facilities-tmp#185]
assign `wkb_geometry` based on `longitude` and `latitude` from source data for
- `sbs_workforce1`
- `nysdoh_nursinghomes`
- `doe_lcgms`
- `hhc_hospitals`
- `dcla_culturalinstitutions`
- `nysed_activeinstitutions `

**Comment by baolingz** [comment]
@AmandaDoyle In the case when the source data have `geom`, `commboard`, `nta`, `council`, `bin`, `bbl`, `censtract` but didn't hit by Geosupport. Should we assign those value via source data or spatial join? 
eg.
```
WITH tmp AS(
SELECT facname, datasource, uid FROM facilities
WHERE geom IS NULL
AND datasource = 'hhc_hospitals'
)
SELECT * FROM hhc_hospitals a, tmp
WHERE a.hash = tmp.uid;
```

**Comment by AmandaDoyle** [comment]
For consistency, take the geometry from the source data.  Then, assign attributes such as `commboard` via a spatial join
