### ISSUE TITLE
dcp_sfpsd

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#190]
MTA missing
```
select distinct pgtable from dcp_sfpsd; 
```
![image](https://user-images.githubusercontent.com/13207770/61894468-80e56200-aede-11e9-916e-62de7fa27cbf.png)
@baolingz  
check data recipe to see if dcp_sfpsd is correctly loaded

**Comment by baolingz** [comment]
@SPTKL @AmandaDoyle `mta_facilities_sfpsd` has been added but `pgtable` = 'rioc_facilities_sfpsd' is missing from the source data.

<img width="256" alt="Screen Shot 2019-07-26 at 10 42 23 AM" src="https://user-images.githubusercontent.com/31453240/61959746-12fa7280-af92-11e9-81eb-30b24b39a21f.png">

**Comment by SPTKL** [comment]
```
select * from facilities_20190110 where datasource ~* 'RIOC';
```

![image](https://user-images.githubusercontent.com/13207770/61962847-78e9f880-af98-11e9-92a2-d1c6da263d1d.png)
