### ISSUE TITLE
dot_mannedfacilities

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-facilities-tmp#193]
Reassign `factype` by combining similar the categories

**Comment by baolingz** [comment]
@AmandaDoyle How to assign `factype` for the following records:
```
SELECT division, operations FROM dot_mannedfacilities
WHERE division = 'N/A'
OR division = 'Multiple';
```
<img width="664" alt="Screen Shot 2019-07-29 at 1 54 29 PM" src="https://user-images.githubusercontent.com/31453240/62070399-6b3aaa00-b208-11e9-8ffb-aefc844a0798.png">

**Comment by AmandaDoyle** [comment]
@SPTKL resolved this issue

**Comment by AmandaDoyle** [comment]
There are still a lot of new facility types that aren't particularly useful coming from this dataset.
Reopening so that we can consolidate facility types

**Comment by AmandaDoyle** [comment]
Assigning to myself.  Will update the facility types

**Comment by AmandaDoyle** [comment]
reduced number of facility types
