### ISSUE TITLE
dca_operatingbusinesses	

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#2]
- [x] load to s3
- [x] build.py
- [x] *.sql

**Comment by baolingz** [comment]
@AmandaDoyle  facsubgrp cannot be defined in sql because 'discipline' field does not exist in raw data.

**Comment by baolingz** [comment]
Code need to be check out to see if there's way to improve run time, eg. Spark. Right now, it takes more than 20 minutes to run the full script.

**Comment by baolingz** [comment]
1. geocoding is unsuccessful with zipcode
2. confirm whether the initial filter is correct

**Comment by baolingz** [comment]
@SPTKL @AmandaDoyle Review Request

**Comment by AmandaDoyle** [comment]
@SPTKL @baolingz 
Here is the old code for loading in legally operating businesses
https://github.com/NYCPlanning/db-facilities/blob/master/2_assembly/config_dca_facilities_operatingbusinesses.sql
A couple things
1) I don't see anything about museums
2) only a subset of these data are loaded into facilities database (see where clause at the end)

**Comment by SPTKL** [comment]
fix .sql file 
```
psql:/home/db-facilities/sql/dca_operatingbusinesses.sql:56: ERROR:  function st_point(character varying, character varying) does not exist
LINE 5:                 THEN ST_SetSRID(ST_Point(longitude, latitude...
                                        ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by baolingz** [comment]
@SPTKL The issue regarding function st_point has been solved.
