### ISSUE TITLE
11 records from doe_busroutesgarages have a NULL or blank factype and as a result blank subgroup

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#209]

**Comment by AmandaDoyle** [comment]
I'm looking at the version on Carto.  This issue does not appear to persist in the version on the server.  Is the dataset not automatically getting updated to the publication database?

**Comment by SPTKL** [comment]
seems to be resolved by itself, just checked on carto, must have been a sync issue
