### ISSUE TITLE
After school programs

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#224]
How should these be grouped / classified?  Put under Education, child welfare and youth, make separate subgroup for after school

**Comment by annmorrisgis** [comment]
This is exactly what I concluded.

**Comment by baolingz** [comment]
I propose to rename the `facsubgrp` as 'Comprehensive After School System (COMPASS) Sites' which is the dycd_afterschoolptrograms used on their [website](https://www1.nyc.gov/site/dycd/services/after-school/comprehensive-after-school-system-of-new-york-city-compass.page) and it's included in the [facilities_classification](https://github.com/NYCPlanning/db-facilities-tmp/blob/dev/referencetables/classification.csv) table as well.

**Comment by AmandaDoyle** [comment]
**EDIT to classification**
Move Afterschool Programs from other health care subgroup as well as
"Beacon After-School Programs", 
"Beacon Satellite After-School Programs,Beacon,NYCHA Community Center". 
"High-School Aged Youth After-School Programs,NDA Programs,Youth Educational Support", "Middle School Youth After-School Programs,NDA Programs,Adolescent Literacy,Youth Educational Support", Teen Action Program After-School Programs" 
to new facsubgrp "After-School Programs" under Education, child welfare and youth

**Comment by baolingz** [comment]
@AmandaDoyle should I move "Out of School Time After-School Programs" and "Out of School Time After-School Programs, Summer Program, Summer Camp" to `facsubgrp` "After-School Programs" as well?
