### ISSUE TITLE
Issues that we need to correct or explain as to what happened - aka incorporate records from COLP

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#227]
Based on comparison of number of records by subgroup between versions:

- [x] Why did we drop EMS stations from COLP?  We have very few EMS stations.  We should bring in EMS stations from COLP.
- [x] We lost a lot of courthouses.  Take Courthouses from COLP when there isn't a record from NYS
- [x] We dropped 21 records and lost the different buildings on Rikers Island.  Need to get back this level of granularity.
- [x] We lost 566 camps, which once came from DOHMH child care inspections.  Is there camp data?  If so we should bring it back in.

**Comment by baolingz** [comment]
We didn't drop EMS from dcas_colp, they are only 4 records in the source data.

**Comment by baolingz** [comment]
we are only missing 49 camps compared to the old version, which could be explained by the massive deduplication we did for `dohmh_daycare`

**Comment by AmandaDoyle** [comment]
We're addressed this issues
