### ISSUE TITLE
Senior centers

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#229]
1) Only take Senior Centers from DFTA data
Do not take Senior centers from MOEO
Remove records that are "NYCHA community centers - senior centers"

2) just make factype Senior Center for all senior centers

**Comment by annmorrisgis** [comment]
Some NYCHA properties are categorized as NORC sites on the facilities database, and on the NYCHA property maps. Do we want to keep these on the facilities database?

**Comment by annmorrisgis** [comment]
Perhaps factypes of "NYCHA Community Center - Senior Program" should also be removed?
