### ISSUE TITLE
Classification: Immigrant Services

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#249]
Move all Immigrant Services facility types into new category

Health and Human Services > Human Services > Immigrant Services

Immigrant Service include but are not limited to:
NDA Immigrants Immigration Services,Immigrant Support Services,NDA Programs,NDA Immigrants

**Comment by baolingz** [comment]
@AmandaDoyle Should we rename the `facsubgrp` 'Youth Centers, Literacy Programs, Job Training, and Immigrant Services' as 'Youth Centers, Literacy Programs and Job Training Centers' since we will make immigrant services on its own?

**Comment by baolingz** [comment]
```
UPDATE dycd_afterschoolprograms
SET facsubgrp = (CASE
			WHEN program = 'Beacon'
			OR program = 'Beacon Satellite'
			OR program = 'High-School Aged Youth'
			OR program = 'Middle School Youth'
			OR program = 'Teen Action Program'
				THEN 'After-School Programs'
			WHEN program_type ~* 'Immigrant Support Services'
				THEN 'Immigrant Services'
			ELSE 'Youth Centers, Literacy Programs, Job Training, and Immigrant Services'
		END)
```

**Comment by baolingz** [comment]
Renamed `facsugrp` "Youth Centers, Literacy Programs, Job Training, and Immigrant Services" as "Youth Centers, Literacy Programs, and Job Training Services" for now, future changes may apply when we take a more comprehensive look at all categories.
