### ISSUE TITLE
Classification: Adult and Immigrant Literacy

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#251]
Move Reading & Writing factype from Other Health Care to
Education, Child Welfare, and Youth > Adult Services > Adult and Immigrant Literacy

Move Adult and Immigrant Literacy Factype programs to 
Education, Child Welfare, and Youth > Adult Services > Adult and Immigrant Literacy

Youth literacy and NDA programs (which are for high school students) should stay under Youth Services

**Comment by baolingz** [comment]
@AmandaDoyle I could not find facilities in `factype` 'Adult and Immigrant Literacy', could you pin me the data source?
