### ISSUE TITLE
Classification: Workforce Development / Other Health

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#254]
Move Workforce Development from Other Health to
Health and Human Services | Human Services | Programs for People with Disabilities | Programs for People with Disabilities

**Comment by baolingz** [comment]
@AmandaDoyle Should I just move it under the`facsubgrp` 'Programs for People with Disabilities' or rename this `factype` to  'Programs for People with Disabilities'  as well?
