### ISSUE TITLE
20 records with a BX borocode but the facilities are located in MN or BK

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#265]
Research records and correct information

**Comment by baolingz** [comment]
Didn't  see this issue in the latest FacDB.
<img width="320" alt="Screen Shot 2019-12-05 at 4 53 24 PM" src="https://user-images.githubusercontent.com/31453240/70277141-cb75c580-177f-11ea-95af-179951b3997c.png">

**Comment by AmandaDoyle** [comment]
This issue still exists
`SELECT * FROM facilities_2 WHERE  boro = 'Bronx' AND (bin::text LIKE '1%' OR bin::text LIKE '3%')`
reveals 21 records where boro = 'Bronx' but the geometry is in Manhattan or Brooklyn

**Comment by AmandaDoyle** [comment]
Fixed
