### ISSUE TITLE
Update the webscraper for nycdoc_corrections

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/db-facilities-tmp#267]
https://www1.nyc.gov/site/doc/about/facilities-locations.page
- ensure all records on Rikers island got covered.

**Comment by AmandaDoyle** [comment]
AD Notes:
 - Have same count of federal `DETENTION AND CORRECTIONAL` facilities (3) (good)
- Missing one NYSDOC facilitity but "Ella McQueen Reception Center for Boys and Girls" which comes from New York State Office of Children and Family Services based on old facilities database.  Maybe need to get record from other source
- City level Rikers island will add 9 more sites, but still maybe missing 10 more sites <-- need to look at records in the old facdb 
`SELECT * FROM dcp_facilities.latest WHERE upper(facsubgrp) LIKE 'DETENTION%AND%CORRECTIONAL' AND overlevel LIKE '%City%'`
and determine if records aren't dups should they be in the FacDB and where do we get them from

**Comment by AmandaDoyle** [comment]
AD note
Facilities we're missing:
Bridges Juvenile Center from NYCDCAS: City Owned and Leased Properties
Brooklyn Family Court NYCDCAS: City Owned and Leased Properties
Bulova Building- DOC Headquarters NYCDCAS: City Owned and Leased Properties;NYCDOC: Correction Facilities Locations
Civil Municipal Court NYCDCAS: City Owned and Leased Properties
Correction Academy NYCDCAS: City Owned and Leased Properties;NYCDOC: Correction Facilities Locations
Crossroads Juvenile Dentent Ct NYCDCAS: City Owned and Leased Properties
Detention Facility NYCDCAS: City Owned and Leased Properties

Field Office-MN Family Ct Divn from NYCDCAS: City Owned and Leased Properties
Hart Island - Potters Field NYCDCAS: City Owned and Leased Properties
Horizon Juvj Ctr/NYPD 40th Pct NYCDCAS: City Owned and Leased Properties
James A. Thomas Center (JATC) NYCDCAS: City Owned and Leased Properties;NYCDOC: Correction Facilities Locations

Queens Criminal Court NYCDCAS: City Owned and Leased Properties

**Comment by AmandaDoyle** [comment]
To fill in missing DETENTION AND CORRECTIONAL facilities:
 **COLP** 
Include records
`where usedec = 'OTHER SECURE DETENTION FACILITY'`
Where name = `DETENTION FACILITY` these records get collapsed into one record

`WHERE usedec = 'JAIL' AND (name LIKE '%COURT%' OR name LIKE '% CT %')`
Records with the same addressed get deduped

From **scraper** https://www1.nyc.gov/site/doc/about/facilities-locations.page
Include `Bulova Building- DOC Headquarters` AND `Correction Academy`

**Comment by AmandaDoyle** [comment]
Last issues:
Change facttype from `Detention and Correctional` to just `CORRECTIONAL FACILITY`

**Comment by AmandaDoyle** [comment]
Still need to correct lat / long and geom for buildings on Rikers Island so that points are on buildings and not in same location

**Comment by AmandaDoyle** [comment]
CORRECTION ACADEMY needs an address and location

**Comment by AmandaDoyle** [comment]
Remaining issues are corrected
