### ISSUE TITLE
Cleanup: 1 record where borocode = 0

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#269]
SELECT * FROM facilities."2019/12/11" WHERE geom IS NOT NULL and borocode = '0';
returns one records that is in Manhattan and the street name = `654 WEST 158TH STREET-EAST OF RI`

NULL out street name 
Make borocode 1

**Comment by baolingz** [comment]
fixed. check 
```
SELECT * FROM facilities
WHERE uid = '70e4515044cdff983705cace56c1ff9b';
```
