### ISSUE TITLE
Rationalize drop in records

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#275]
Explain why we see a drastic drop in the following subgroups

- [x] PARKING LOTS AND GARAGES where data source is dca_operatingbusinesses (commercial parking lots)
- [x] PARKING LOTS AND GARAGES where data source is dot_publicparking (public parking) - what is public parking supposed to be?
- [x] Feeding sites - removed all these but what did they get absorbed into?

**Comment by baolingz** [comment]
```
SELECT a.facname, a.address, a.boro, a.factype, b.facname,b.address, b.boro, b.factype FROM facilities a
RIGHT JOIN dcp_facilities b
ON UPPER(a.facname||a.address) = UPPER(b.facname||b.address)
WHERE UPPER(b.factype) = 'FEEDING SITE'
AND a.datasource = 'nysed_activeinstitutions';
```
There are 98 records in current facilities having the same `facname||address` as what are under `factype` 'Feeding sites' in old FacDB, which all come  from `nysed_activeinstitutions`.

**Comment by baolingz** [comment]
We've removed records form 'dca_operatingbusinesses' for those having expired permits which drop the number of records from 1063 to 345
```
SELECT * FROM dca_operatingbusinesses.latest
WHERE industry = 'Parking Lot'
AND address_borough != 'Outside NYC';
```

**Comment by baolingz** [comment]
```
SELECT * FROM dot_publicparking.latest;
```
There are only 44 records from `dot_publicparking` source data, from which 38 of them have been fed into facilities.

**Comment by AmandaDoyle** [comment]
I don't think we're missing "Feeding sites" based on what is in the source dataset

**Source data**
<img width="1406" alt="Screen Shot 2019-12-17 at 2 22 31 PM" src="https://user-images.githubusercontent.com/5611960/71027222-cfd3a400-20d8-11ea-833b-42941a45abcb.png">

**data engineering facdb**
<img width="1531" alt="Screen Shot 2019-12-17 at 2 12 27 PM" src="https://user-images.githubusercontent.com/5611960/71027241-d95d0c00-20d8-11ea-86fd-66654c3a6a2a.png">

**FacDB in production**
<img width="1266" alt="Screen Shot 2019-12-17 at 2 11 17 PM" src="https://user-images.githubusercontent.com/5611960/71027291-f2fe5380-20d8-11ea-9ff5-d36dba661d80.png">

**Comment by AmandaDoyle** [comment]
I don't think we're missing records WHERE factype = 'Public Parking'

FacDB in production got records from http://www.nyc.gov/html/dot/html/motorist/parkinglist.shtml

We received data directly from DOT which is consistent with what is on the website
