### ISSUE TITLE
dep_wwtc

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#28]
- [x] load to s3
- [x] build.py
- [x] *.sql

Website: https://www1.nyc.gov/html/dep/html/wastewater/wwsystem-plants.shtml

Scrape website.  Put machine readable table in github repo, then load into S3 etc.

**Comment by SPTKL** [comment]
issues observed: 
- there's no address for all the locations
- no previous sql code for guidance

**Comment by AmandaDoyle** [comment]
@SPTKL confirmed with @lseirup 
Go ahead and manually create the data table and save it in the repo

It looks like these records used to come from the old facilities database (https://github.com/NYCPlanning/db-facilities/blob/master/2_assembly/config_dcp_facilities_sfpsd.sql)
So go ahead and draft a new SQL template and we'll review it

**Comment by baolingz** [comment]
@AmandaDoyle @SPTKL 
I found a map on NYCcommon, which might be worth digging into for address info. Not sure about the source credibility. After applying the filter 'waterfront' and 'Department of Environmental Protection, you will get wwtp with address info.
https://nycommons.org/#map=11/40.7353/-73.9153&layers=%5B%22waterfront%22%5D&owners=%7B%22waterfront%22%3A%5B29%5D%7D&boundaries=%7B%7D

**Comment by AmandaDoyle** [comment]
https://www1.nyc.gov/site/dep/water/wastewater-treatment-plants.page
Updated link ^
@baolingz I'd suggest not using the map because we cannot verify the source data
