### ISSUE TITLE
foodbankny_foodbanks

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#29]
- [x] s3 
- [x] py
- [x] sql

Data are available here: https://www.foodbanknyc.org/wp-admin/admin-ajax.php?action=asl_load_stores&nonce=83cc04ac0d&load_all=0&layout=1&lat=40.7983474111969&lng=-73.9395518&nw%5B%5D=41.15908281222903&nw%5B%5D=-74.4614023859375&se%5B%5D=40.43761201016478&se%5B%5D=-73.4177012140625

**Comment by SPTKL** [comment]
- seems like source data has major schema change 
- unable to identify `facname`, `opname`, and not sure if mappings for `factype` are correct

**Comment by AmandaDoyle** [comment]
@SPTKL  The mapping of 
`WHEN categories = '64' THEN 'Food Pantry' WHEN categories = '65' THEN 'Soup Kitchen'`
Is correct, but what do we do if 
A)  one facility has more than one category.  In the past we've kept both all records (i.e. one record for the food pantry, one records for the soup kitchen) so let's continue doing that.  
B) The category is neither 64 or 65?
63 = Senior Center (potentially duplicative with dfta_contracts).  Facility subgroup would be `Senior Services`
66 = SNAP Center (potentially duplicative with hra_centers).  Facility subgroup would be `Financial Assistance and Social Services`
67 = Kosher Center Facility subgroup would be `Soup Kitchens and Food Pantries`

I'd advocate that we include all facilities and then deduplicate the data later
