### ISSUE TITLE
2020 March Update - nysdoh_nursinghomes

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#290]
### Issue: 
deduplication for nysdoh_nursinghomes
(consider a group by for all different beds) 

there's no `Total Residential Beds` nor `Total Adult Day Health Care Capacity`
previous logic: 
```sql
factype = (CASE
WHEN "bed_type/service_category" = 'Total Residential Beds' THEN 'Nursing Home'
WHEN "bed_type/service_category" = 'Total Adult Day Health Care Capacity' THEN 'Adult Day Care'
 END),

facsubgrp = (CASE
WHEN "bed_type/service_category" = 'Total Residential Beds' THEN 'Residential Health Care'
WHEN "bed_type/service_category" = 'Total Adult Day Health Care Capacity' THEN 'Other Health Care'
END),

captype = (CASE
WHEN "bed_type/service_category" = 'Total Residential Beds' THEN 'beds'
WHEN "bed_type/service_category" = 'Total Adult Day Health Care Capacity' THEN 'seats'
END), 
```

> ADHCPSLOTSAV, Adult Day Health Care Slots Available
> BIBEDSAV, Behavioral Intervention Beds Available
> DIALYSISDEN, Dialysis Station Dens
> NHBEDSAV, Nursing Home Beds Available
> PEDBEDSAV, Pediatric Beds Available
> PEDVENTCAP, Pediatrics Ventilator Beds
> SCATTERBEDSAV, Scatter Ventilator Beds Available
> TBIBEDSAV, Traumatic Brain Injury Beds Available
> VENTBEDSAV, Ventilator Beds Available

### Solution: 
Nursing Home Beds Available --> Total Residential Beds --> *beds*
Adult Day Health Care Slots Available --> Total Adult Day Health Care Capacity or everything other than Nursing Home Beds sumed? --> *seats*?

**Comment by AmandaDoyle** [comment]
@SPTKL I think your solution works here because every distinct facility has a record where bed_type = 'NHBEDSAV' OR bed_type = 'ADHCPSLOTSAV'
So you'll only take records where bed_type = 'NHBEDSAV' OR bed_type = 'ADHCPSLOTSAV'
WHEN bed_type = 'NHBEDSAV' THEN 'Nursing Home'
WHEN  bed_type = 'NHBEDSAV'  THEN 'Adult Day Care'
and workflow continues as documented

**Comment by SPTKL** [comment]
implemented
