### ISSUE TITLE
2020 March Update - foodbankny_foodbank

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#291]
### Issue: 
repeated facilities with both food pantry and soup kitchen, should we dedup? they do have different factype

**Comment by AmandaDoyle** [comment]
@SPTKL Soup Kitchens and Food Pantries can coexist and are not duplicates
https://capitalplanning.nyc.gov/facility/37b45fda452c554b7a45843567f0269a#15.85/40.6843/-73.9692

**Comment by SPTKL** [comment]
implemented
