### ISSUE TITLE
2020 March Update - hra_centers

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#292]
### Issue: 
+ How to assign subgroup? new factypes: 
> CASA OFFICE
> JOBS AND SERVICE CENTER
> MEDICAID OFFICE
> OCSS CENTER
> SNAP CENTER

+ previous logic: 
```sql
(CASE 
WHEN type = 'Job Center' THEN 'Workforce Development'
ELSE 'Financial Assistance and Social Services'
END),
```
### Solution: 
OCSS CENTER (Office of Child Support Services) --> Financial Assistance and Social Services ?
CASA (Home Care Services) --> Financial Assistance and Social Services ?

**Comment by AmandaDoyle** [comment]
@SPTKL For this update let's continue to scrape from the website since I'm not finding what's on open data to be a 1:1 match to what's on the website, but it's worth digging into on a later date to see if we should switch.
You solution for OCSS and CASA centers is correct

**Comment by SPTKL** [comment]
implemented
