### ISSUE TITLE
nysed_nonpublicenrollment

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#32]
- [x] s3
- [ ] .py
- [ ] .sql

**Comment by AmandaDoyle** [comment]
Take latest Nonpublic Enrollment by Grade from http://www.p12.nysed.gov/irs/statistics/nonpublic/

http://www.p12.nysed.gov/irs/statistics/nonpublic/2018-19_NonPub_EnrollmentbyGrade.xlsx

name table nysed_nonpublicenrollment

**Comment by SPTKL** [comment]
@AmandaDoyle dataset has no address info, but there's BEDS code, maybe there could be an BEDS code - address lookup table somewhere?
