### ISSUE TITLE
qpl_libraries

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#34]
- [x] s3
- [ ] py
- [ ] sql

https://data.cityofnewyork.us/Education/Queens-Library-Branches/kh3d-xhq7

For Queens Public Libraries

  facname = name,
  factype = 'Public Library',
  facsubgrp = 'Public Libraries',
  facgroup = NULL,
  facdomain = NULL,
  servarea = NULL,
  opname = Queens Public Library,
  opabbrev = QPL,
  optype = Public, <-- this should be assigned in the SQP general query
  overagency = Queens Public Library,
  overabbrev = QPL,
  overlevel = NULL, <-- this should be assigned in the SQP general query
  capacity = NULL,
  captype = NULL,
  proptype = NULL
For Brooklyn Public Libraries

  facname = title,
  factype = 'Public Library',
  facsubgrp = 'Public Libraries',
  facgroup = NULL,
  facdomain = NULL,
  servarea = NULL,
  opname = Brooklyn Public Library,
  opabbrev = BPL,
  optype = Public, <-- this should be assigned in the SQP general query
  overagency = Brooklyn Public Library,,
  overabbrev = BPL,
  overlevel = NULL, <-- this should be assigned in the SQP general query
  capacity = NULL,
  captype = NULL,
  proptype = NULL

**Comment by SPTKL** [comment]
https://db-data-recipes.sfo2.digitaloceanspaces.com/pipelines/db-facilities/2019-05-14/datapackage.json

**Comment by baolingz** [comment]
ERROR:  function st_point(character varying, character varying) does not exist
LINE 5:                 THEN ST_SetSRID(ST_Point(longitude, latitude...
                                        ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
you might have to cast longitude and latitude as `double precision`

**Comment by baolingz** [comment]
The issue regarding function st_point has been solved.
