### ISSUE TITLE
dca_operatingbusinesses boro code conversion issue

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#36]
- in existing code, only converts queens/brooklyn/the bronx/new york to boroughs (NY, BX, BK, QN, SI) using the field `city`
- however, there are cities in the queens, for example `woodside`, `jackson heights`, that are completely ignored/filtered out of the final dataset 

### Solution: 
- geocode with zipcode and set all boro code to ' ' 
- if zipcode is not in NYC, there would be an error message recorded saying zipcode cannot be found in geosupport

**Comment by baolingz** [comment]
@SPTKL Bugs fixed. Please review.
