### ISSUE TITLE
remove lib from etl folder

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#37]
-issue: current folder /etl/lib is causing disruptions for production
- solution:
-- remove the `lib` directory from `etl`
-- for management purposes, we will put all dataflows related custom functions in the `lib` directory in `root`
-- to run functions in lib, do `pip install -e .` in root directory
-- read more about managing modules here

https://docs.python.org/3/tutorial/modules.html

**Comment by baolingz** [comment]
@SPTKL removed
