### ISSUE TITLE
confirm attributes for qpl_libraries and bql_libraries 

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#38]
here are the following attributes that have uncertainties:
- [ ] facname = name,
- [ ] factype = 'Public Library',
- [ ] facsubgrp = 'Public Libraries',	
- [ ] facgroup = NULL,
- [ ] facdomain = NULL,
- [ ] servarea = NULL,
- [ ] opname = ???, 
- [ ] opabbrev = ???,
- [ ] optype = 'Non-public',
- [ ] overagency = ???,
- [ ] overabbrev = ???, 
- [ ] overlevel = NULL, 
- [ ] capacity = NULL, 
- [ ] captype = NULL, 
- [ ] proptype = NULL

**Comment by AmandaDoyle** [comment]
For Queens Public Libraries
- [ ] facname = name,
- [ ] factype = 'Public Library',
- [ ] facsubgrp = 'Public Libraries',	
- [ ] facgroup = NULL,
- [ ] facdomain = NULL,
- [ ] servarea = NULL,
- [ ] opname = Queens Public Library,
- [ ] opabbrev = QPL,
- [ ] optype = Public, <-- this should be assigned in the SQP general query
- [ ] overagency = Queens Public Library,
- [ ] overabbrev = QPL, 
- [ ] overlevel = NULL, <-- this should be assigned in the SQP general query
- [ ] capacity = NULL, 
- [ ] captype = NULL, 
- [ ] proptype = NULL

For Brooklyn Public Libraries
- [ ] facname = title,
- [ ] factype = 'Public Library',
- [ ] facsubgrp = 'Public Libraries',	
- [ ] facgroup = NULL,
- [ ] facdomain = NULL,
- [ ] servarea = NULL,
- [ ] opname = Brooklyn Public Library,
- [ ] opabbrev = BPL,
- [ ] optype = Public, <-- this should be assigned in the SQP general query
- [ ] overagency = Brooklyn Public Library,,
- [ ] overabbrev = BPL, 
- [ ] overlevel = NULL, <-- this should be assigned in the SQP general query
- [ ] capacity = NULL, 
- [ ] captype = NULL, 
- [ ] proptype = NULL
