### ISSUE TITLE
dcp_pops	

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#5]
- [x] s3
- [ ] py
- [ ] sql

**Comment by AmandaDoyle** [comment]
@SPTKL POPS_Export_Public_Official_Records(2019-5-22_15.0).csv was emailed by Stella and I uploaded the dataset to the FTP dcp

**Comment by SPTKL** [comment]
@AmandaDoyle which overagency should be assigned to pops? in previous script, it's parks + DOB saved in an array.

**Comment by AmandaDoyle** [comment]
@SPTKL Edit the python script so that we use the geometry directly from the source data, and do not overwrite the geometry with the lat / long that comes from GeoSupport (we should do this for all "Park" types)

**Comment by baolingz** [comment]
ERROR:  function st_point(character varying, character varying) does not exist
LINE 5:                 THEN ST_SetSRID(ST_Point(longitude, latitude...
                                        ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
you might have to cast longitude and latitude as `double precision`

**Comment by baolingz** [comment]
The issue regarding function st_point has been solved.
