### ISSUE TITLE
nypl_libraries

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#58]
The NYPL dataset on open data hasn't been updated since June 21, 2013.  Can we scrape the data from this website https://www.nypl.org/locations/list?  Maybe this link https://refinery.nypl.org/api/nypl/locations/v1.0/locations?callback=angular.callbacks._1
NYPL covers Manhattan, the Bronx, and Staten Island

- [x] s3
- [ ] .py
- [ ] .sql

**Comment by baolingz** [comment]
ERROR:  function st_point(character varying, character varying) does not exist
LINE 5:                 THEN ST_SetSRID(ST_Point(longitude, latitude...
                                        ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
you might have to cast longitude and latitude as `double precision`

**Comment by baolingz** [comment]
The issue regarding function st_point has been solved.
