### ISSUE TITLE
doe_universalprek	

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#8]

**Comment by SPTKL** [comment]
potential sources: 
https://maps.nyc.gov/prek/#map-page
https://maps.nyc.gov/prek/data/pka/pka.csv?1558717200000
https://maps.nyc.gov/prek/data/pka/pka.csv

**Comment by AmandaDoyle** [comment]
@lseirup you can get data behind https://maps.nyc.gov/prek/#map-page
See https://maps.nyc.gov/prek/data/pka/pka.csv
But we think that there's a chance that the data are being pulled from open data and repackaged (https://data.cityofnewyork.us/Education/Universal-Pre-K-UPK-School-Locations/kiyv-ks3f)
Next step: compare pka.csv to open data set and determine if we use pka.csv as the data source

**Comment by AmandaDoyle** [comment]
@SPTKL @baolingz 
Confirmed: use the data that you can download from the map here
https://maps.nyc.gov/prek/data/pka/pka.csv?1558717200000 (aka Map)

It's different than what's on open data

**Comment by AmandaDoyle** [comment]
Sorry it took me so long to get to this

The data that you download from here https://maps.nyc.gov/prek/data/pka/pka.csv?1558717200000 (aka Map), which drives the map, is different than what you download from the open data portal here https://data.cityofnewyork.us/api/views/kiyv-ks3f/rows.csv?accessType=DOWNLOAD (aka Open data)

Key differences found so far (both datasets downloaded today, June 6th): 
Open data: 1885 records; Map: 1895 records
Map has different capacity values for PreK, 3K, EL; Open data only has one capacity field: seats
It's estimated that 261 records appear in Map and not in Open Data.  This is based on seeing which location codes appear in Map and not in Open Data.
