### ISSUE TITLE
moeo_socialservicesiteloactions

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#85]
location FTP: /agencysourcedata/moeo

This dataset replaces the HHS dataset

Flag me to review field mapping once you have first draft

Notes from the meeting about the dataset
Attendees: Martha Norrick, Director of Data Strategy; Sujin Lee, Business Intelligence Analyst; Adam
__HHS Accelerator__ – created during Bloomberg administration to handle contracts for a subset of health and human services agencies. This function has been moved to Mayor’s Office of Contract Services. MOCS has a new online portal for procurement called PASSPort, which will include updates to service delivery locations.

__HHS Connect__ was developed so that case workers could see data on clients across multiple datasets. This is now called Worker Connect, and is part of MOEO.

OneNYC 2015 included an initiative to create better data on location of services. MOEO created this using data from HHS Accelerator and Checkbook. Took a year to collect and clean the data, so the information is at least a year old.  Have data from ACS, DOP (Probation), DOHMH, DSS, DYCD, and DFTA. __Martha says that we should pull DYCD and DFTA data from NYC Open Data, as it will be more current.__

They used a data model adapted from Greg Bloom’s Open Referral model. This is overly complicated and they plan to revise it. Rather than figure out the files on Open Data, __they will send us a flat file to use for this FacDB update.__ They hope to have a revised model in the new few months.

They are building out an on-line form for agencies to update information like service locations. They do not include capacity information in the dataset because they felt that it would always be out-of-date. Data can be used to equity analysis looking distribution of services, but not referrals.

**Comment by AmandaDoyle** [comment]
[Social_Service_Site_Location_DCP_052319 (1).xlsx](https://github.com/NYCPlanning/db-facilities-tmp/files/3267061/Social_Service_Site_Location_DCP_052319.1.xlsx)

**Comment by brentginsberg** [comment]
Attached is Joy's initial mapping analysis between SSSLD program name and FacDB's facility type/facility subgroup. There are rows highlighted in red/yellow that need some further research and determination.

[Social_Service_DCP_Facility_SiteMatching_190626.xlsx](https://github.com/NYCPlanning/db-facilities-tmp/files/3336365/Social_Service_DCP_Facility_SiteMatching_190626.xlsx)

**Comment by AmandaDoyle** [comment]
[Social_Service_DCP_Facility_SiteMatching_190710_v4.xlsx](https://github.com/NYCPlanning/db-facilities-tmp/files/3387646/Social_Service_DCP_Facility_SiteMatching_190710_v4.xlsx)

Attached is Joy's final mapping analysis between SSSLD program name and FacDB's facility subgroup. The program names highlighted in red should be excluded from FacDB.  The program name will be the facility type.

**Comment by baolingz** [comment]
@AmandaDoyle how to define the following fields?
`facname` = ??
`opabbrev` = ??
`optype` = ??

**Comment by AmandaDoyle** [comment]
facname = `PROVIDER_NAME` + `PROGRAM_NAME`
opabbrev = `NULL`
Operator is PROVIDER_NAME so there is no abbreviation 
optype = `Non-public`

**Comment by baolingz** [comment]
@AmandaDoyle There are 5173 records in `moeo_socialservicesiteloactions` but only 1626 records after applying `SELECT COUNT(DISTINCT(provider_name||program_name)) FROM moeo_socialservicesiteloactions;` Should I deduplicate for facilities for those having same `facname` and `site_address_1`?

**Comment by baolingz** [comment]
@AmandaDoyle There are 19 `program_name` categories missing in the manually match table, which are ABUSE PREVENTION, AFTERSCHOOL PROGRAMS, CAREGIVER, CASE MANAGEMENT ONLY, FAMILY SUPPORT, GERIATRIC MENTAL HEALTH, HOME CARE, HOME DELIVERED MEALS, HOME DELIVERED MEALS ONLY, IMMIGRANT SERVICES, JOBS & INTERNSHIPS, NEW YORK CONNECTS, NORC SITES, READING & WRITING, RUNAWAY & HOMELESS YOUTH, SENIOR CENTER, SENIOR CENTER AFFILIATED SITE, SOCIAL SERVICES ONLY, TRANSPORTATION ONLY.

The following are the `facsubgrp` mapping suggestions
```
UPDATE moeo_socialservicesiteloactions
SET facsubgrp = (CASE
                                      WHEN program_name = 'JOBS & INTERNSHIPS' 
                                              THEN 'Workforce Development'
                                      WHEN program_name = 'GERIATRIC MENTAL HEALTH' 
                                              THEN 'Mental Health'
                                      ELSE 'Other Health Care'
```

**Comment by baolingz** [comment]
@AmandaDoyle @brentginsberg Need to confirm whether there is an input error. The `program_name` which are 'NON-MEDICAID CARE COORDINATION; (NON-LICENSED PROGRAM)' and 'NON-MEDICAID CARE COORDINATION (OMH)' will be assigned different `facsubgrp`. The `facsubgrp` 'Health Care' hasn't been defined in `facility_classification` table.
<img width="1546" alt="Screen Shot 2019-07-16 at 2 51 34 PM" src="https://user-images.githubusercontent.com/31453240/61321298-3dea0700-a7d9-11e9-8609-555854d4244a.png">

**Comment by AmandaDoyle** [comment]
Ah sorry I missed this 

Yes, deduplicate for facilities for those having same `facname` and `address`

@brentginsberg @amirapu 
Those 19 program names listed above are not mapped to a subgroup.  Can you confirm that you're okay with @baolingz logic?
