### ISSUE TITLE
dohmh_daycare	

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities-tmp#9]

**Comment by AmandaDoyle** [comment]
This dataset contains a list of all inspections.  What we want is each unique location.  I suggest taking the latest record (most recent Inspection Date) for each unique 

- [ ] foo
- [x]

**Comment by baolingz** [comment]
SQL script needs to be updated (adding filters according to above instructions)

**Comment by SPTKL** [comment]
resolved after using simplified geosupport API
![image](https://user-images.githubusercontent.com/13207770/59929123-299b3000-940e-11e9-95eb-2421bbbbd36d.png)
