### ISSUE TITLE
nysocfs_offices

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-facilities-tmp#99]
- [x] s3 
- [ ] py
- [ ] sql
https://ocfs.ny.gov/main/regionaloffices_main.asp
Need locations within the five boroughs

**Comment by SPTKL** [comment]
Note: only took new york region --> which covers all facilities in new york city

**Comment by baolingz** [comment]
@AmandaDoyle No guidance for sql script, need to define the following field:
- [ ] 	facsubgrp = ??,

**Comment by AmandaDoyle** [comment]
putting on hold for right now to make sure that we're taking the right records

**Comment by AmandaDoyle** [comment]
Confirmed with @lseirup - not loading into FacDB
